package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import modelo.Vehiculo;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class PanelController implements Initializable{
	@FXML
	private Button botoningresar;
	@FXML
	private TableView<Vehiculo> tblVehiculo;
	@FXML
	private TableColumn coluPlaca;
	@FXML
	private TableColumn columfecha;
	@FXML
	private Button botosalir;
	@FXML
	private TextField textplaca;
	@FXML
	private ChoiceBox tipo ;
	private ObservableList<Vehiculo> vehiculos;
    
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		   // Creo el observablelist
		tipo.getItems().add("Moto");
		tipo.getItems().add("Carro");
		
        vehiculos = FXCollections.observableArrayList();
        // Asigno las columnas con los atributos del modelo
        this.coluPlaca.setCellValueFactory(new PropertyValueFactory("Placa"));
        this.columfecha.setCellValueFactory(new PropertyValueFactory("fecha"));

	}
	// Event Listener on Button[#botoningresar].onAction
	@FXML
	public void ingresar(ActionEvent event) {
		// TODO Autogenerated
		 try {

	            // Obtengo los datos del formulario
	            String placa = this.textplaca.getText();
	            String fecha = "21/10/2022";
	

	            // Creo una persona
	            Vehiculo p = new Vehiculo(placa,fecha);
                 System.out.println(p.getPlaca()+""+ p.getFecha());
	            // Compruebo si la persona esta en el lista
	            if (!this.vehiculos.contains(p)) {
	                // Lo añado a la lista
	                this.vehiculos.add(p);
	                // Seteo los items
	                this.tblVehiculo.setItems(vehiculos);
	            } else {
	            	// Es una alerta cuando ya esta en el sistema
	                Alert alert = new Alert(Alert.AlertType.ERROR);
	                alert.setHeaderText(null);
	                alert.setTitle("Error");
	                alert.setContentText("El vehiculo ya ha sido  registrado");
	                alert.showAndWait();
	            }
	        } catch (NumberFormatException e) {
// Es una alerta que el formato es incorrecto
	            Alert alert = new Alert(Alert.AlertType.ERROR);
	            alert.setHeaderText(null);
	            alert.setTitle("Error");
	            alert.setContentText("Formato incorrecto");
	            alert.showAndWait();
	        }
	}
	
    private void seleccionar(MouseEvent event) {

        // Obtengo la persona seleccionada
        Vehiculo p = this.tblVehiculo.getSelectionModel().getSelectedItem();

        // Sino es nula seteo los campos
        if (p != null) {
            this.textplaca.setText(p.getPlaca());

        }

    }
	// Event Listener on Button[#botosalir].onAction
	@FXML
	public void salir(ActionEvent event) {
		// TODO Autogenerated
        // Obtengo la persona seleccionada
        Vehiculo p = this.tblVehiculo.getSelectionModel().getSelectedItem();

        // Si la persona es nula, lanzo error
        if (p == null) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setHeaderText(null);
            alert.setTitle("Error");
            alert.setContentText("Debes seleccionar el vehiculo");
            alert.showAndWait();
        } else {

            // La elimino de la lista
            this.vehiculos.remove(p);
            // Refresco la lista
            this.tblVehiculo.refresh();
         // Es un aviso que el vehiculo ya se retiro 
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setHeaderText(null);
            alert.setTitle("Info");
            alert.setContentText("Vehiculos ha salido");
            alert.showAndWait();

        }
	}

}
